spring:
  application:
    name: bootu-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hankorion/bootu-config-repo.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka/